services:
   redis:
     image: redis/redis-stack:6.2.6-v19
     container_name: redis
     ports:
       - "6379:6379"
   qdrant:
     image: qdrant/qdrant
     container_name: qdrant
     ports:
       - "6333:6333"